### ISSUE TITLE
Nix packaging & testing

### ISSUE THREAD

**Issue by RaitoBezarius** [Nix-Security-WG/nix-security-tracker#12]
Security tracker should be packaged as a classical Django web application (potentially some JS stuff if really needed…).

I should be able to do `nix-build -A app` and get a Python ecosystem where I can run `gunicorn ...` to run the server.

Inspiration can be taken from https://github.com/mangaki/mangaki/tree/master/nix.

Anything that offers:

- Trivial VM tests to verify we can deploy in a VM the whole suite
- Testing the migration works
- Testing the seeding works

would be awesome.

Then, this can be integrated further in CI (modulo KVM problems in GHA), we could use Hercules-CI for that.

**Comment by fricklerhandwerk** [comment]
This is done.
