### ISSUE TITLE
Background task management

### ISSUE THREAD

**Issue by RaitoBezarius** [Nix-Security-WG/nix-security-tracker#14]
The security tracker will do a lot of things on its own in the background.

What do we go for the orchestration?

We can start with something very simple like https://github.com/Opus10/django-pgpubsub and reuse PostgreSQL capabilities instead of rolling an extra piece of software in the deployment.

We can use cronjobs and store in the database and have a management command that executes all of them and we just have a systemd unit that polls for it.

**Comment by fricklerhandwerk** [comment]
This is done, there's a worker for ingestion that runs periodically.
