### ISSUE TITLE
Bulk triaging of automatic suggestions

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#178]
As a security team member, I want to be able to quickly work off a triaging backlog of automatic suggestions that match CVEs with packages, by dismissing the suggestions or promoting them to the next triaging stage.

In order to do this, I want to:
-  #203

Given that list of suggestions, I want to

- #190
- #189
- #210
- #209
- #206
- #207
- #187
- #200

# Notes

- The list should be available instantly.
- It also needs to work well on mobile, as this is an activity that people might do to fill breaks.

**Comment by erictapen** [comment]
As a security team members, I want the task of creating a Nix security issue to be as low-effort entry as possible. It also needs to work well on mobile, as this is an activity that people might do to fill breaks.

Suggestions are pre-compiled, this means the user can quickly (as in low load time) be presented with a list of suggestions.

When seeing a list of suggestions, each suggestion should allow me to do the following check, in order of visual importance:

- [ ] Does the **CVE title/project name** refer to the proposed **Nix package name**
- [ ] Is the **CVE Severity score** high enough to spend my time on it for now?
- [ ] Do the **CVE Version constraints** match the **Nix package Versions in any of our active channels**?
- [ ] Does the **CVE description** offer additional context that this is in fact not a match?

Coming from these I would be able to take the following paths, ordered by friction:

- [ ] Do nothing for now
- [ ] Decide that this is a match, open a new Nix security issue
- [ ] Send a link of a suggestion to a peer for consultation? *Unsure wether it would be wiser to just create the issue and then break it apart when in question.*
- [ ] Decide that this is in fact not a match, which will either create a new suggestion or another 
- [ ] Decide that this CVE doesn't concern Nixpkgs at all

It should generally be easy to mark a match. It should be hard to flag a false negative.

**Comment by fricklerhandwerk** [comment]
>  Send a link of a suggestion to a peer for consultation? *Unsure wether it would be wiser to just create the issue and then break it apart when in question.*

Our records have a status (affected, wonfix, ...) which should be modifiable and its history shown in #169.

**Comment by erictapen** [comment]
Okay, so you mean that the workflow in this case would be just to create the Nix security issue in question, send it to a peer and then close it for wontfix, if it turns out to be irrelevant?

**Comment by fricklerhandwerk** [comment]
Closing this -- what now amounts to a -- tracking issue in favor of the milestones that chunk up the completion of the workflows:
- https://github.com/Nix-Security-WG/nix-security-tracker/milestone/1
- https://github.com/Nix-Security-WG/nix-security-tracker/milestone/2
