### ISSUE TITLE
Periodically generate a full database dump

### ISSUE THREAD

**Issue by proofconstruction** [Nix-Security-WG/nix-security-tracker#198]
Currently, ingesting the full CVE list and a copy of nixpkgs can take several hours, dramatically reducing iteration speed.

To facilitate faster development, it would be useful to asynchronously generate DB dumps and cache them for easy downloading by developers.

**Comment by erictapen** [comment]
What's the URL endpoint for the downloadable dumps now? Didn't see that at first glance.

**Comment by RaitoBezarius** [comment]
https://dumps.sectracker.nixpkgs.lahfa.xyz/

**Comment by erictapen** [comment]
@RaitoBezarius the action is failing currently, so only one dump from 12 days is available on the bucket. Could you have a look? I'm still dumping directly from the staging host to get a working db, which is time consuming.

https://github.com/Nix-Security-WG/nix-security-tracker/actions/runs/11433700475/job/31806093828#step:9:18

**Comment by fricklerhandwerk** [comment]
Restoring the dump fails for me with:

```
pg_restore: processing data for table "public.shared_nixderivationmeta_source_provenances"
pg_restore: processing data for table "public.shared_nixderivationoutput"
pg_restore: error: could not uncompress data: incorrect data check
```

**Comment by RaitoBezarius** [comment]
Can you provide a reproducer?

**Comment by fricklerhandwerk** [comment]
I'm following [the steps in CONTRIBUTING.md](https://github.com/Nix-Security-WG/nix-security-tracker/blob/main/CONTRIBUTING.md#set-up-a-local-container). Maybe the download was incomplete or something, I'll try again.

**Comment by fricklerhandwerk** [comment]
Okay it seems being in a certain region of Germany messes up routing. It works from my VPS in Frankfurt...

**Comment by RaitoBezarius** [comment]
@fricklerhandwerk Can you run from your weird German region:
```
$ tracepath dumps.sectracker.nixpkgs.lahfa.xyz          
```

and show me the result?

**Comment by fricklerhandwerk** [comment]
Another problem is that the dump is not being made periodically. There seems to be a problem with the GitHub Action.
