### ISSUE TITLE
View a list of pre-computed match suggestions

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#203]
As a security team member, I want to have an overview of untriaged CVEs, displayed as a priority list.

Each item in that list should only show the most relevant information:
  - CVE ID
  - CVE logline
  - Number of derivations affected
  - Number of channels affected
  
 The list should be sorted by some reasonable combination of
 - CVE age
 - CVE severity
 - Relevance for Nixpkgs (e.g. number of supposedly affected derivations)
 - Confidence in the matching of CVE and Nixpkgs metadata
 
 Depends on:
 - #221

**Comment by erictapen** [comment]
@fricklerhandwerk @RaitoBezarius and me discussed, that we will keep the concept of a match suggestion separate from a Nix security issue. That applies both to the internal model and how it's communicated to the user.

**Comment by erictapen** [comment]
![tmp yRLhZ2GsEM](https://github.com/user-attachments/assets/bc6fa432-de1f-4543-bc26-776bba181028)
![tmp 2jPHitPcr2](https://github.com/user-attachments/assets/118f79fe-d131-4e9b-9ab3-9c727fd44f09)

The wireframes we want to work with for now. From now I'll focus on implementation, to see how this works with real data.

**Comment by erictapen** [comment]
Provenance of how the match was created could be represented in some background colors of the relevant fields
https://github.com/Nix-Security-WG/nix-security-tracker/pull/282
