### ISSUE TITLE
GitHub sync doesn't run in production

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#239]
[Deployment through the module uses `daphne`](https://github.com/Nix-Security-WG/nix-security-tracker/blob/main/nix/web-security-tracker.nix#L217-L218), while the initial sync is [only run when doing `manage runserver`](https://github.com/Nix-Security-WG/nix-security-tracker/blob/main/src/website/shared/apps.py#L15).

Make sure deployment always syncs on startup and sync can be ran manually in development mode.

**Comment by RaitoBezarius** [comment]
I think this is quite brittle for production, the logic should be extracted to a management command, run as part of the ExecStartPre, it can be kept for development purpose there.

**Comment by fricklerhandwerk** [comment]
Updated the description
