### ISSUE TITLE
Parameterize GitHub org and team settings

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#240]
As a contributor, in my development shell I want to conveniently override application settings, such as the org and teams to sync with.

Currently one can't run the service locally without manually changing the [GitHub parameters](https://github.com/Nix-Security-WG/nix-security-tracker/blob/main/src/website/tracker/settings.py#L281-L287), or manually [create a `USER_SETTINGS_FILE`](https://github.com/Nix-Security-WG/nix-security-tracker/blob/main/src/website/tracker/settings.py#L295-L303). There is a way to [generate that file programmatically](https://github.com/Nix-Security-WG/nix-security-tracker/blob/main/nix/web-security-tracker.nix#L22-L24) which is accessible to the module.

Extract that functionality into a helper script that is available in the devshell and will create the right thing from an untracked directory, e.g.

```
.settings
├── GH_COMMITTERS_TEAM
├── GH_ORGANIZATION
└── GH_SECURITY_TEAM
```

**Comment by proofconstruction** [comment]
What does this accomplish that just creating the `USER_SETTINGS_FILE` doesn't?

**Comment by fricklerhandwerk** [comment]
The workflow is documented in CONTRIBUTING.md and has a bit of helper code in default.nix for the shell
