### ISSUE TITLE
Logging should not be WARNING for management scripts

### ISSUE THREAD

**Issue by RaitoBezarius** [Nix-Security-WG/nix-security-tracker#245]
`ingest_bulk_cve` uses WARNING to log information, it should be INFO.

**Comment by RaitoBezarius** [comment]
Slowly being fixed by #265 as well.

**Comment by RaitoBezarius** [comment]
There's still one instance: `ingest_manual_evaluation`.

**Comment by fricklerhandwerk** [comment]
Fixed by https://github.com/Nix-Security-WG/nix-security-tracker/pull/272
