### ISSUE TITLE
Optimize query for suggestions list

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#288]
The query on the suggestion view currently takes too long to demo

**Comment by erictapen** [comment]
Fixed by https://github.com/Nix-Security-WG/nix-security-tracker/pull/292, right?

**Comment by fricklerhandwerk** [comment]
No:

> All that remains is adding the right indexes to optimize the main queries. https://github.com/Nix-Security-WG/nix-security-tracker/pull/292#issue-2618045692

**Comment by erictapen** [comment]
Oops, sorry

**Comment by RaitoBezarius** [comment]
With the newest PR #378, the target is to cache anything that triggers additional queries, currently with 378, the cve_id triggers a needless fetch.

**Comment by fricklerhandwerk** [comment]
Closed by #378
