### ISSUE TITLE
Store the version of a derivation in the database

### ISSUE THREAD

**Issue by erictapen** [Nix-Security-WG/nix-security-tracker#294]
Currently we only have the `name` attribute available in the db. Either provide a good utility function that works similar to `builtins.parseDrvName` or figure out the version while evaluating Nixpkgs and put it in the db right away.

**Comment by RaitoBezarius** [comment]
This may require parsing the `.drv` file in the end, cc #58.

**Comment by fricklerhandwerk** [comment]
Why can't we take the `version` attribute from the evaluation?

**Comment by fricklerhandwerk** [comment]
We could have a `Maybe Version` as a stopgap though, no need to build the drv parser at this point (yet).

**Comment by fricklerhandwerk** [comment]
As discussed the week before last with @erictapen, we can also copy the implementation of `nix-env` version parsing, it's not that hard.
