### ISSUE TITLE
Categorize Nixpkgs branch names into families

### ISSUE THREAD

**Issue by erictapen** [Nix-Security-WG/nix-security-tracker#295]
A "family" would be something like the 24.05 release, containing `nixos-24.05-small`, `nixos-24.05`, `nixpkgs-24.05-darwin` etc. A family can be end of life, unstable or stable.

There is already the `NixChannel` class representing some of that information. It would be good to have an additional utility function, that provides that structure to the suggestions view. Also we need to make sure that this is future proof, e.g. when the NixOS release cadence changes again in the future.

**Comment by RaitoBezarius** [comment]
This may require parsing the `.drv` file in the end, cc #58.
