### ISSUE TITLE
View derivation description in suggestion view

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#333]
As a security team member, while triaging I want to know what a derivation is about, and for that I need to at least see the short description string right in the suggestion.

Blocked by:
- https://github.com/Nix-Security-WG/nix-security-tracker/issues/359 (we'd need a useful data dump to iterate on the UI)

**Comment by erictapen** [comment]
Blocked by https://github.com/Nix-Security-WG/nix-security-tracker/issues/338

**Comment by fricklerhandwerk** [comment]
#388 is closed now, unblocked.

**Comment by fricklerhandwerk** [comment]
@RaitoBezarius @Erethon Blocked by https://github.com/Nix-Security-WG/nix-security-tracker/issues/359 and https://github.com/Nix-Security-WG/nix-security-tracker/issues/198 since we also don't have a working eval availabe on staging, and we're using that to pull fresh DB dumps. @erictapen  and I can work around this by spending time to set up a local eval, but it would be a better use of everyone's time if we didn't and could focus on UX tasks.
