### ISSUE TITLE
Sort dismissed and selected views by last update

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#356]
When triaging matching suggestions and inspecting dismisses/selected entries, I want to see those items I most recently moved around at the top of the list.

(Currently they are sorted in seemingly unpredictable order.)

**Comment by fricklerhandwerk** [comment]
Discussed with @erictapen and @RaitoBezarius :
- set `updated_at` if and only if the state was changed, and sort by `updated_at` in the view
- we'll have richer information in the [activity log](https://github.com/Nix-Security-WG/nix-security-tracker/issues/169), but that will take time to arrive and will require a more expensive query anyway

**Comment by erictapen** [comment]
small addition: we need to override the update_ad field, as it is auto-updating otherwise.

**Comment by fricklerhandwerk** [comment]
Note from @alejandrosame: Currently there seems to be no transaction around the combination of change state and removing derivations; need to look into that.
