### ISSUE TITLE
Set up and connect a cache

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#377]
We have very complex aggregate data that requires long queries, but once compiled the data is largely immutable. In order to leverage that and reduce response times, we need a cache that can be accessed across requests, e.g. Redis.

Update the deployment such that the webserver has access to the cache, and add an integration test to verify that it works.

**Comment by RaitoBezarius** [comment]
I am not convinced the case was demonstrated for query set caching, so I strongly do not recommend pursuing this until we have exhausted all the optimization opportunities we have (and we have plenty of them).

**Comment by fricklerhandwerk** [comment]
Closing for now as https://github.com/Nix-Security-WG/nix-security-tracker/pull/378 fixes the problem this was supposed to address.
