### ISSUE TITLE
Removed suggestions show up in selected view

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#396]
In the triage view, after removing derivations from a suggestion and clicking "select" or "dismiss", the derivations are shown again on the suggestion in the respective other view.

Implementation notes:
- This is an issue the cache not getting updated
- @RaitoBezarius proposed to not change the suggestion at all, but merely store markers for which derivations where removed and compute the desired result in the view.

**Comment by erictapen** [comment]
One attempt to fix this, was https://github.com/Nix-Security-WG/nix-security-tracker/pull/384, but it will probably be closed.

**Comment by RaitoBezarius** [comment]
> @RaitoBezarius proposed to not change the suggestion at all, but merely store markers for which derivations where removed and compute the desired result in the view.

Correction: apply the change to the suggestion _and_ the cached variant.

**Comment by fricklerhandwerk** [comment]
Closed by https://github.com/Nix-Security-WG/nix-security-tracker/pull/384
