### ISSUE TITLE
Set up GitHub parameters and secrets for staging

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#398]
The staging deployment currently doesn't start because it's not wired up with GitHub.

Follow-up on https://github.com/Nix-Security-WG/nix-security-tracker/issues/239

**Comment by alejandrosame** [comment]
Fixed with https://github.com/Nix-Security-WG/nix-security-tracker/pull/460 and https://github.com/Nix-Security-WG/nix-security-tracker/pull/402.
