### ISSUE TITLE
Remove derivations instantly

### ISSUE THREAD

**Issue by fricklerhandwerk** [Nix-Security-WG/nix-security-tracker#411]
Make it work the same as removing suggestions.

**Comment by erictapen** [comment]
Not sure I can maintain the current noJS workflow here. Would it be okay if the page reloads for every package that is deselected when JavaScript is disabled?

**Comment by fricklerhandwerk** [comment]
Oof, that would be a hard degradation. What's the limitation here? Having an extra endpoint for updating just one derivation?

**Comment by erictapen** [comment]
Nah, the difficulty would be to have the same HTML document handle both cases. But it might work, I'll report back.

**Comment by erictapen** [comment]
I think I managed to do it, see #423
