### ISSUE TITLE
Summarise changes in the activity log display

### ISSUE THREAD

**Issue by erictapen** [Nix-Security-WG/nix-security-tracker#425]
![tmp wOxkuJahh3](https://github.com/user-attachments/assets/fad9f5b4-b4d1-4795-b83b-8040f8c06b8d)

**Comment by fricklerhandwerk** [comment]
Ah, this is because we're not removing them in one transaction since the htmx stuff. How about debouncing and batching the removal, e.g. by only sending a bulk request when
- the suggestion scrolls out of view
- when the state changes
- some timer runs out?

**Comment by erictapen** [comment]
Mh I don't like breaking the promise, that changes are immediate. What if the user closes the browser tab before scrolling further?

**Comment by fricklerhandwerk** [comment]
Yeah, I was just thinking we'd have to put roughly the same logic for grouping changes into either component. But I guess if we issue a random token with each static page, grouping by that token will be a pretty good approximation.

**Comment by erictapen** [comment]
Ah I was just thinking about grouping by time delta tbh. Everything from the same user within 5min distance should be grouped together.

**Comment by alejandrosame** [comment]
If we are to group by time delta, how should the ISO timestamps be displayed?

For example, should it be displayed as the first and last timestamp like `2024-11-26T11:38:41+00:00 to 2024-11-26T11:43:41+00:00`?

**Comment by fricklerhandwerk** [comment]
I'd keep it simple and only display the last one.
