### ISSUE TITLE
Draft is being displayed on the untriaged suggestions page

### ISSUE THREAD

**Issue by erictapen** [Nix-Security-WG/nix-security-tracker#455]
On [current staging](https://sectracker.nixpkgs.lahfa.xyz/suggestions/), I can see suggestions that were marked as draft and still show up on the untriaged suggestions page. I don't understand what the last entry in the activity log means, but either this is a draft being wrongly displayed on /suggestions or mweinelt was able to turn the status back into an automatic suggestion, which should be impossible.

![tmp kDUGNLpQak](https://github.com/user-attachments/assets/2434e68a-8bbf-4daf-abef-f62ec5e4b9d2)

**Comment by fricklerhandwerk** [comment]
This is because we're not grouping undos and not showing a state name
