### ISSUE TITLE
Triage CVEs using automatic suggestions

### ISSUE THREAD

**Issue by RaitoBezarius** [Nix-Security-WG/nix-security-tracker#5]
As a security team member, I may have a lot of untriaged CVEs, but a lot of them are noise.
I would like to focus on anything that could be related to Nixpkgs. For this, I need automatic suggestions based on weighted correlation analysis between CVEs and Nixpkgs metadata.

This is a record linkage problem: https://en.wikipedia.org/wiki/Record_linkage.

- [x] Full text search and manually link CVEs and packages into a Nixpkgs security record
  - https://github.com/Nix-Security-WG/nix-security-tracker/pull/167
- #178
- #177

  For example, given a CVE on a software A on version range [R1, R2], I would like to have a list of candidates from Nixpkgs that can match this CVE and quickly triage if this is a non-problem, or if we are affected and on which channels.

- #6
- [ ] #216

**Comment by fricklerhandwerk** [comment]
Closing this -- what now amounts to a -- tracking issue in favor of the milestones that chunk up the completion of the workflows:
- https://github.com/Nix-Security-WG/nix-security-tracker/milestone/1
- https://github.com/Nix-Security-WG/nix-security-tracker/milestone/2
