### ISSUE TITLE
[Tracking Issue] Deployment

### ISSUE THREAD

**Issue by RaitoBezarius** [Nix-Security-WG/nix-security-tracker#60]
- [x] Cron for ingesting the bulk CVE
- [x] Cron for cloning nixpkgs somewhere and maintaining up-to-date
- [ ] #175

**Comment by fricklerhandwerk** [comment]
Closing this tracking issue in favor of [milestones](https://github.com/Nix-Security-WG/nix-security-tracker/milestones).
