### ISSUE TITLE
Regular notifications

### ISSUE THREAD

**Issue by RaitoBezarius** [Nix-Security-WG/nix-security-tracker#9]
As a user, maintainer, or security team member, I want to get notifications on security issues I care about.

- #174
- [ ] Subscription management
  - #173
  - #171
    -  (e.g. age, severity, package, channel, maintainer status, ...)
  - #179
- #172
- #170

**Comment by fricklerhandwerk** [comment]
Discussed with @erictapen and @proofconstruction:
- Notifications should probably mostly GitHub driven
  - This is a lot cheaper and leverages existing workflows
  - e.g. assign people to issues, post comments with information and @-mentions

**Comment by fricklerhandwerk** [comment]
Closing the tracking issue in favor of [milestones](https://github.com/Nix-Security-WG/nix-security-tracker/milestones).
